%% Convert data into appropriate units, quantities

sweeprate = (tableB(:,8)-tableB(:,7))./tableB(:,9);
sweepstart = tableB(:,7);
peak_1_freq = tableB(:,5).*sweeprate + sweepstart;
peak_2_freq = tableB(:,6).*sweeprate + sweepstart;
instr_uncert = ones(size(tableB,1),1)*0.001;

%% Varying Z-coil current

zrange = [1:9 11:15];

z_mag_field = i2b(tableB(:,3),'z');

[x, i] = sort(z_mag_field(zrange));
y1 = peak_1_freq(zrange(i));
y2 = peak_2_freq(zrange(i));
sig=instr_uncert(zrange(i));

%% Error analysis for Z-coil

% error in determination of current
uncert_I = 0.1; % coil ammeters quote current to +-0.1mA
uncert_I_B = i2b(uncert_I,'z'); % convert current uncert to magentic field
dBdI = i2b(1,'z')^2;

% error in coil geometry (specifically radius)
R_Z = 11.0*2.54*0.01;1; % radius of coil in metres
uncert_R_B = 0.0040; % uncertainty in coil radius in metres (estimated)
dBdR = i2b(tableB(:,3)/R_Z,'z'); % dB/dR
dBdR = dBdR(zrange(i)); % sort them into the correct order

% total error in magnetic field
uncert_B = sqrt(uncert_I_B^2*dBdI + uncert_R_B^2*dBdR.^2);

% convert magnetic field error to frequency^2 uncertainty for coil 1
grads = zeros(size(y1,1),1);
diffs = diff(y1.^2)./diff(x);
grads(2:end-1) = (diffs(1:end-1) + diffs(2:end))/2; % generate derivative of f^2 w.r.t. b
grads(1) = diffs(1);
grads(end) = diffs(end);
sig1 = grads.*uncert_B + sig;

% convert magnetic field error to frequency^2 uncertainty for coil 2
grads = zeros(size(y2,1),1);
diffs = diff(y2.^2)./diff(x);
grads(2:end-1) = (diffs(1:end-1) + diffs(2:end))/2; % generate derivative of f^2 w.r.t. b
grads(1) = diffs(1);
grads(end) = diffs(end);
sig2 = grads.*uncert_B + sig;


%% Plot Z-coil data
% 
% figure
% hold on
% errorbar(y_mag_field(yrange),peak_1_freq(yrange),instr_uncert(yrange),'*r')
% errorbar(y_mag_field(yrange),peak_2_freq(yrange),instr_uncert(yrange),'*')
% xlabel('Magnetic field generated by Y-coil [G]')
% ylabel('Resonance frequency of absorption peaks [kHz]')
% title('Resonance peak movement as Y-coil current varies')
% 
% % indicates Iy_earth is -19.3mA

figure
hold all
%errorbar((z_mag_field(zrange)+0.1902).^2,peak_1_freq(zrange).^2,instr_uncert(zrange),'*r')
%errorbar((z_mag_field(zrange)+0.1902).^2,peak_2_freq(zrange).^2,instr_uncert(zrange),'*')
Zlin1 = linearFit((z_mag_field(zrange)+0.1902).^2,peak_1_freq(zrange).^2,sig1)
Zlin2 = linearFit((z_mag_field(zrange)+0.1902).^2,peak_2_freq(zrange).^2,sig2)
xlabel('$$(b_z-b_{z,geo}^2,$$ [G]$$^2$$')
ylabel('$$f^2 $$[kHz]$$^2$$')
title('Linear relationship between $$B_z^2$$ and $$f^2$$ :: Z-coil')
legend('Peak 1 Fit', 'Peak 1 Data','Peak 2 Fit', 'Peak 2 Data')

% 
%% Fit hyperbolas (nonlin) :: Y
% %Peak1
% function_hyperbola  = @(x,a) a(1).*(1+((x+a(3))./a(2)).^2).^(1/2)+a(4);
% a0=[67 0.13 0.06 -7];
% 
% xlab='Magnetic field generated by Y-coil [G]';
% ylab='Resonance frequency of absorption peaks [kHz]';
% tit1='Resonance peak movement as Y-coil current varies: Peak 1';
% 
% [a1,aerr1] = fitnonlin(xlab,x,ylab,y1,tit1,sig,function_hyperbola,a0)
% 
% %Peak2
% a0=[87 0.11 0.06 1.4];
% 
% tit2='Resonance peak movement as Y-coil current varies: Peak 2';
% 
% [a2,aerr2] = fitnonlin(xlab,x,ylab,y2,tit2,sig,function_hyperbola,a0)
% 
% 
%% Fit hyperbolas (lin) :: Y
% 
% %Peak1
% [p S] = polyfit(x, y1.^2,2);  % is a row vector representing the result of the polyfit
% xpoly1 = p(1)*x.^2 + p(2)*x + p(3);
% bearth_y = -0.5*p(2)/p(1);  % calculate b_{earth,y} from C/B in chris's notation
% 
% figure()
% hold on
% plot(x, xpoly1, 'r')
% plot(x, y1.^2, 'b*')
% xlabel('Magnetic field generated by Y-coil [G]')
% ylabel('f_{res}^2 [kHz^2]')
% title('Y coil -- Peak 1 (linear fit)')
% gtext({['f_{res}^2 = ' num2str(p(1)) ' b_z^2 + ' num2str(p(2)) ' b_z + ' num2str(p(3))],...
%     ['b_{earth,y} = ' num2str(bearth_y) ' G']})
% 
% %Peak2
% [p S] = polyfit(x, y2.^2,2);  % is a row vector representing the result of the polyfit
% xpoly2 = p(1)*x.^2 + p(2)*x + p(3);
% bearth_y = -0.5*p(2)/p(1);  % calculate b_{earth,y} from C/B in chris's notation
% 
% figure()
% hold on
% plot(x, xpoly2, 'r')
% plot(x, y2.^2, 'b*')
% xlabel('Magnetic field generated by Y-coil [G]')
% ylabel('f_{res}^2 [kHz^2]')
% title('Y coil -- Peak 2 (linear fit)')
% gtext({['f_{res}^2 = ' num2str(p(1)) ' b_z^2 + ' num2str(p(2)) ' b_z + ' num2str(p(3))],...
%     ['b_{earth,y} = ' num2str(bearth_y) ' G']})

%% Plot hyperbolas lin rnd 2 baybay -- Z

%Peak1
[p,C,chi2]=linFitWithConstant(x.^2,x,y1.^2,sig1);
xpoly = [x(1):abs(x(end)-x(1))/100:x(end)];
ypoly1 = p(1)*xpoly.^2 + p(2)*xpoly + p(3);
bearth_z1 = -0.5*p(2)/p(1);  % calculate b_{earth,z} from C/B in chris's notation
uncert_bearth_z1 = sqrt((0.5/p(1))^2 * (C(2,2) + (p(2)/p(1))^2 * C(1,1)));

figure()
hold on
plot(xpoly, ypoly1, 'r')
errorbar(x, y1.^2,sig1,'b*')
xlabel('Magnetic field generated by Z-coil [G]')
ylabel('$$f_{res}^2$$ [kHz]$$^2$$')
title('Z coil -- Peak 1 (linear fit)')
gtext({['$$f_{res}^2 = ' num2str(p(1)) ' b_z^2 + ' num2str(p(2)) ' b_z + $$' num2str(p(3))],...
    ['$$b_{earth,z} = ' num2str(bearth_z1) ' \pm ' num2str(uncert_bearth_z1) '$$ G'],...
    ['$$\chi^2 = $$' num2str(chi2)]})

%Peak2
[p,C,chi2]=linFitWithConstant(x.^2,x,y2.^2,sig2);
ypoly2 = p(1)*xpoly.^2 + p(2)*xpoly + p(3);
bearth_z2 = -0.5*p(2)/p(1);  % calculate b_{earth,z} from C/B in chris's notation
uncert_bearth_z2 = sqrt((0.5/p(1))^2 * (C(2,2) + (p(2)/p(1))^2 * C(1,1)));

figure()
hold on
plot(xpoly, ypoly2, 'r')
errorbar(x, y2.^2,sig2,'b*')
xlabel('Magnetic field generated by Z-coil [G]')
ylabel('$$f_{res}^2$$ [kHz]$$^2$$')
title('Z coil -- Peak 2 (linear fit)')
gtext({['$$f_{res}^2 = ' num2str(p(1)) ' b_z^2 + ' num2str(p(2)) ' b_z + $$' num2str(p(3))],...
    ['$$b_{earth,z} = ' num2str(bearth_z2) ' \pm ' num2str(uncert_bearth_z2) ' $$G'],...
    ['$$\chi^2 = $$' num2str(chi2)]})

%% Clean up :: Z

clear zrange z_mag_field xlab ylab tit1 tit2 x y1 y2 sig...
    function_hyperbola a0 i xpoly1 p S a1 aerr1 a2 aerr2...
    xpoly1 xpoly2 C chi2 uncert_I uncert_I_B dBdI R_Y uncert_R_B dBdR...
    uncert_B sig1 sig2 grads diffs R_Z

%% General clean up

clear sweeprate sweepstart peak_1_freq peak_2_freq instr_uncert