%% Convert data into appropriate units, quantities

sweeprate = (tableF(:,8)-tableF(:,7))./tableF(:,9);
sweepstart = tableF(:,7);
peak_1_freq = tableF(:,5).*sweeprate + sweepstart;
peak_2_freq = tableF(:,6).*sweeprate + sweepstart;
instr_uncert = ones(size(tableF,1),1)*0.001;

%% Varying Y-coil current

yrange = [1:15];

y_mag_field = i2b(tableF(:,2),'y');

[x i] = sort(y_mag_field(yrange));
y1 = peak_1_freq(yrange(i));
y2 = peak_2_freq(yrange(i));
sig=instr_uncert(yrange(i));


%% Plot Y-coil data

figure
hold on
errorbar(y_mag_field(yrange),peak_1_freq(yrange),instr_uncert(yrange),'*r')
errorbar(y_mag_field(yrange),peak_2_freq(yrange),instr_uncert(yrange),'*')
xlabel('Magnetic field generated by Y-coil [G]')
ylabel('Resonance frequency of absorption peaks [kHz]')
title('Resonance peak movement as Y-coil current varies')

% indicates Iy_earth is -19.3mA

%% Fit hyperbolas (nonlin) :: Y
%Peak1
function_hyperbola  = @(x,a) a(1).*(1+((x+a(3))./a(2)).^2).^(1/2)+a(4);
a0=[67 0.13 0.06 -7];

xlab='Magnetic field generated by Y-coil [G]';
ylab='Resonance frequency of absorption peaks [kHz]';
tit1='Resonance peak movement as Y-coil current varies: Peak 1';

[a1,aerr1] = fitnonlin(xlab,x,ylab,y1,tit1,sig,function_hyperbola,a0)

%Peak2
a0=[87 0.11 0.06 1.4];

tit2='Resonance peak movement as Y-coil current varies: Peak 2';

[a2,aerr2] = fitnonlin(xlab,x,ylab,y2,tit2,sig,function_hyperbola,a0)


%% Fit hyperbolas (lin) :: Y

%Peak1
[p S] = polyfit(x, y1.^2,2);  % is a row vector representing the result of the polyfit
xpoly1 = p(1)*x.^2 + p(2)*x + p(3);
bearth_y = -0.5*p(2)/p(3);  % calculate b_{earth,y} from C/B in chris's notation

figure()
hold on
plot(x, xpoly1, 'r')
plot(x, y1.^2, 'b*')
xlabel('Magnetic field generated by Y-coil [G]')
ylabel('f_{res}^2 [kHz^2]')
title('Y coil -- Peak 1 (linear fit)')
gtext({['f_{res}^2 = ' num2str(p(1)) ' b_z^2 + ' num2str(p(2)) ' b_z + ' num2str(p(3))],...
    ['b_{earth,y} = ' num2str(bearth_y) ' G']})

%Peak2
[p S] = polyfit(x, y2.^2,2);  % is a row vector representing the result of the polyfit
xpoly2 = p(1)*x.^2 + p(2)*x + p(3);
bearth_y = -0.5*p(2)/p(3);  % calculate b_{earth,y} from C/B in chris's notation

figure()
hold on
plot(x, xpoly2, 'r')
plot(x, y2.^2, 'b*')
xlabel('Magnetic field generated by Y-coil [G]')
ylabel('f_{res}^2 [kHz^2]')
title('Y coil -- Peak 2 (linear fit)')
gtext({['f_{res}^2 = ' num2str(p(1)) ' b_z^2 + ' num2str(p(2)) ' b_z + ' num2str(p(3))],...
    ['b_{earth,y} = ' num2str(bearth_y) ' G']})

%% Clean up :: Y

clear yrange y_mag_field xlab ylab tit1 tit2 x y1 y2 sig...
    function_hyperbola a0 i xpoly1 bearth_y p S a1 aerr1 a2 aerr2...
    xpoly1 xpoly2

%% Varying X-coil current

xrange = [16:27];

x_mag_field = i2b(tableF(:,1),'x');

[x i] = sort(x_mag_field(xrange));
y1 = peak_1_freq(xrange(i));
y2 = peak_2_freq(xrange(i));
sig=instr_uncert(xrange(i));

%% Plot X-coil data

figure
hold on
errorbar(x_mag_field(xrange),peak_1_freq(xrange),instr_uncert(xrange),'*r')
errorbar(x_mag_field(xrange),peak_2_freq(xrange),instr_uncert(xrange),'*')
xlabel('Magnetic field generated by X-coil [G]')
ylabel('Resonance frequency of absorption peaks [kHz]')
title('Resonance peak movement as X-coil current varies')

% indicates Ix_earth is 148.5mA

%% Fit hyperbolas (nonlin) :: X

%Peak1
function_hyperbola  = @(x,a) a(1).*(1+((x+a(3))./a(2)).^2).^(1/2)+a(4);
a0=[52 -0.1 -0.36 4];

xlab='Magnetic field generated by X-coil [G]';
ylab='Resonance frequency of absorption peaks [kHz]';
tit='Resonance peak movement as X-coil current varies: Peak 1';

[a1,aerr1] = fitnonlin(xlab,x,ylab,y1,tit,sig,function_hyperbola,a0)

%Peak2
a0=[87 -0.1 -0.36 -4];

xlab='Magnetic field generated by X-coil [G]';
ylab='Resonance frequency of absorption peaks [kHz]';
tit='Resonance peak movement as X-coil current varies: Peak 2';

[a2,aerr2] = fitnonlin(xlab,x,ylab,y2,tit,sig,function_hyperbola,a0)

%% Fit hyperbolas (lin) :: X

%Peak1
[p S] = polyfit(x, y1.^2,2);  % is a row vector representing the result of the polyfit
xpoly1 = p(1)*x.^2 + p(2)*x + p(3);
bearth_x = -0.5*p(2)/p(3);  % calculate b_{earth,x} from C/B in chris's notation

figure()
hold on
plot(x, xpoly1, 'r')
plot(x, y1.^2, 'b*')
xlabel('Magnetic field generated by X-coil [G]')
ylabel('f_{res}^2 [kHz^2]')
title('X coil -- Peak 1 (linear fit)')
gtext({['f_{res}^2 = ' num2str(p(1)) ' b_z^2 + ' num2str(p(2)) ' b_z + ' num2str(p(3))],...
    ['b_{earth,x} = ' num2str(bearth_x) ' G']})

%Peak2
[p S] = polyfit(x, y2.^2,2);  % is a row vector representing the result of the polyfit
xpoly2 = p(1)*x.^2 + p(2)*x + p(3);
bearth_x = -0.5*p(2)/p(3);  % calculate b_{earth,y} from C/B in chris's notation

figure()
hold on
plot(x, xpoly2, 'r')
plot(x, y2.^2, 'b*')
xlabel('Magnetic field generated by X-coil [G]')
ylabel('f_{res}^2 [kHz^2]')
title('X coil -- Peak 2 (linear fit)')
gtext({['f_{res}^2 = ' num2str(p(1)) ' b_z^2 + ' num2str(p(2)) ' b_z + ' num2str(p(3))],...
    ['b_{earth,x} = ' num2str(bearth_x) ' G']})

%% Clean up :: X

clear xrange x_mag_field xlab ylab tit x y1 y2 sig function_hyperbola a0 i...
    xpoly1 xpoly2 p S bearth_x a1 aerr1 a2 aerr2


%% Varying Z-coil current
% 
% zrange = [28:];
% 
% z_mag_field = i2b(tableF(:,1),'z');
% 
% figure
% hold on
% errorbar(z_mag_field(zrange),peak_1_freq(zrange),instr_uncert(zrange),'*r')
% errorbar(z_mag_field(zrange),peak_2_freq(zrange),instr_uncert(zrange),'*')
% xlabel('Magnetic field generated by Z-coil [G]')
% ylabel('Resonance frequency of absorption peaks [kHz]')
% title('Resonance peak movement as Z-coil current varies')
% 
% clear zrange z_mag_field 

%% General clean up

clear sweeprate sweepstart peak_1_freq peak_2_freq instr_uncert